//objects used to initialize imageObjects
var animations =
  [
  ['okmaybenot',
  {name: 'every',
  width: 1500,
  height: 500,
  context: canvas.getContext('2d'),
  source: 'img/every.png',
  numberOfFrames: 3,
  ticksPerFrame: 5,
  framesToPlay: 60,},
  {name: 'maybe1',
  width: 500,
  height: 500,
  context: canvas.getContext('2d'),
  source: 'img/maybe.png',
  numberOfFrames: 1,
  ticksPerFrame: 1,
  framesToPlay: 3},
  {name: 'every2',
  width: 1500,
  height: 500,
  context: canvas.getContext('2d'),
  source: 'img/every.png',
  numberOfFrames: 3,
  ticksPerFrame: 5,
  framesToPlay: 60,},
  {name: 'maybe2',
  width: 500,
  height: 500,
  context: canvas.getContext('2d'),
  source: 'img/maybe.png',
  numberOfFrames: 1,
  ticksPerFrame: 1,
  framesToPlay: 3},
  {name: 'every3',
  width: 1500,
  height: 500,
  context: canvas.getContext('2d'),
  source: 'img/every.png',
  numberOfFrames: 3,
  ticksPerFrame: 5,
  framesToPlay: 45},
  {name: 'not',
  width: 500,
  height: 500,
  context: canvas.getContext('2d'),
  source: 'img/not.png',
  numberOfFrames: 1,
  ticksPerFrame: 3,
  framesToPlay: 9}
  ],
  ['vomit_zombie',
  {name: 'vomit_zombie',
  width: 4352,
  height: 256,
  context: canvas.getContext('2d'),
  source: 'img/vomit_zombie.png',
  numberOfFrames: 17,
  ticksPerFrame: 5,
  framesToPlay: 85}
  ],
  ['funny_monster',
  {name: 'funny_monster',
  width: 850,
  height: 18,
  context: canvas.getContext('2d'),
  source: 'img/funny_monster_25.png',
  numberOfFrames: 25,
  ticksPerFrame: 5,
  framesToPlay: 75}
  ],
  ['8_bit_inv_77',
  {name: '8_bit_inv_77',
  width: 33172,
  height: 312,
  context: canvas.getContext('2d'),
  source: 'img/8_bit_inv_77.png',
  numberOfFrames: 77,
  ticksPerFrame: 5,
  framesToPlay: 77}
  ],
  ['8_bit_adv_158',
  {name: '8_bit_adv_158',
  width: 33315,
  height: 500,
  context: canvas.getContext('2d'),
  source: 'img/8_bit_adv_158.png',
  numberOfFrames: 158,
  ticksPerFrame: 5,
  framesToPlay: 158}
  ]
];
